### ISSUE TITLE
Perlin noise generation broken for negative coordinates

### ISSUE THREAD

**Issue by I3ck** [colinhect/hsnoise#1]
The noise generation seems to be broken for negative coordinates (hard edges, big areas of very similar values)
The cause might be related to https://gamedev.stackexchange.com/questions/121797/strange-1d-perlin-noise-generation-with-negative-x-values  

## left: negative x values, right: positive ones
![noisegen](https://user-images.githubusercontent.com/6945711/29004510-c442d6c8-7ac8-11e7-9d56-5468ca13ea75.png)
## center is origin
![noisegen2](https://user-images.githubusercontent.com/6945711/29004531-2af510ca-7ac9-11e7-91a9-75c00878d5e6.png)

**Comment by endash** [comment]
Just ran into this myself. It's interestingly patterned, random enough that for a while I thought it was working and that the problem was with some matrix multiplication I was doing elsewhere.

<img width="333" alt="Screen Shot 2019-05-23 at 10 36 54 AM" src="https://user-images.githubusercontent.com/20806/58261711-d4083080-7d46-11e9-8167-16c2487e6ff4.png">

(Top is normal, bottom flips the x coordinate to negative)

**Comment by endash** [comment]
The problem seems to be https://github.com/colinhect/hsnoise/blob/master/src/Numeric/Noise.hs#L43 (and L45, L47.) `floor` doesn't just truncate the decimal, so there's an off-by-one error here. Replacing those lines with just `floor <var>` fixes the problem:

<img width="336" alt="Screen Shot 2019-05-23 at 11 05 01 AM" src="https://user-images.githubusercontent.com/20806/58263764-a3c29100-7d4a-11e9-87d1-40d5ad97a52d.png">

(Top normal, bottom flipped x-coordinate)

**Comment by colinhect** [comment]
Thanks for the fix!

**Comment by Syntax-Programmer** [comment]
@endash  Thanks for the fix, I am so happy that my implementation works after 2 days of debugging
